### ISSUE TITLE
AAS property value is not modified with the REST PUT request

### ISSUE THREAD

**Issue by Huang2Ning** [eclipse-basyx/basyx-java-sdk#106]
Dear team,

I had a problem when changing AAS Property values with the PUT request. And here's my example :
I started with a GET value of the property. (ParkStatus = 0)
![image](https://user-images.githubusercontent.com/33783614/183598449-6276df00-f69f-4a8b-affd-9aa3917a2c0f.png)
Now I want to change the status from 0 to 1, I tired PUT 1 to the previous URL where I got the value but it is not working with a 500 error.
![image](https://user-images.githubusercontent.com/33783614/183599075-1b5a5b72-384a-4017-815e-a535fed7e784.png)
Then I tried to GET something from xxxxx/ParkStatus instead of xxxxx/ParkStatus/value. And here it shows the value=0, we are sure the  value wasn't changed. 
![image](https://user-images.githubusercontent.com/33783614/183599554-4b374a3e-8a5f-42ff-9952-1fccdbec7bde.png)
I copied all the results to the request body and changed here value=1. It worked.
![image](https://user-images.githubusercontent.com/33783614/183599985-a4036b38-19c4-4984-8d8f-636f37a9b7dd.png)
I redo a GET to see if the value is changed successfully. (ParkStatus = 1)
![image](https://user-images.githubusercontent.com/33783614/183600745-26eeb345-8ffe-49df-a174-92155f3e515d.png)
After that I try to PUT a value (0)  to directly from URL xxxxx/ParkStatus/value again, this time it worked.
![image](https://user-images.githubusercontent.com/33783614/183601211-446f24d5-30db-4425-8f1b-0be525cbfdbf.png)
The value has been changed from 1 to 0
![image](https://user-images.githubusercontent.com/33783614/183601328-3007a39f-1c00-4f15-92a1-2d8c17371ab5.png)

For each time I lanch the AAS server I have to pass these steps above to finally PUT value to /value URL directly. I'm really looking forward to your reply. Thank you ;)

**Comment by FrankSchnicke** [comment]
Hi,

this looks rather strange. Would it be possible to provide us with your application code so that we can reproduce this issue on our side?

Best regards,
Frank

**Comment by Huang2Ning** [comment]
Hello, thank you for your response. When I add the code below 		`valDelOperationalData_Storage_Number.setSetHandler(dew::set_OperationalData_Storage_Number);`
