### ISSUE TITLE
IOUtils  class not found exceptoion by calling AASXToMetamodelConverter.retrieveAASBundles()

### ISSUE THREAD

**Issue by naabbassi** [eclipse-basyx/basyx-java-sdk#107]
I tried to convert an aasx bundles to metamodel using this util class in basyx-sdk vresion 1.2.0-RC1.

there is an issue with commons-io method IOUtils.copy 

```
AASXToMetamodelConverter aasxConverter = new AASXToMetamodelConverter(new ByteArrayInputStream(fileContents));
aasxConverter.retrieveAASBundles()
```

method  -> `IOUtils.copy(stream, writer, StandardCharsets.UTF_8);`

the exception is as follows : 

```
threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils] with root cause
java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
```

**Comment by FrankSchnicke** [comment]
Does this issue also persist with the 1.2.0 release?

**Comment by naabbassi** [comment]
I tried with Basyx-SDK version 1.2.0, and unfortunately the same error appears.

![image](https://user-images.githubusercontent.com/2658530/187196251-124ffd35-6db3-4ac0-a0d7-2224886f07dc.png)

**Comment by FrankSchnicke** [comment]
I could not replicate your issue on my side. Do the tests in TestAASXToMetamodelConverterFromFile.java (org.eclipse.basyx.testsuite.regression.aas.factory.aasx) pass on your setup?

**Comment by naabbassi** [comment]
actually our project has apache-commons-io as a dependency but only for test purposes and was defined in pom.xml in test scope. roughly speaking wrong scope of dependency caused the error.

**Comment by naabbassi** [comment]
actually our project had apache-common-io as a dependency but only for test purposes and was defined in pom.xml in test scope. roughly speaking wrong scope of dependency caused the error.
