### ISSUE TITLE
Lambda properties and operations with pushed AAS

### ISSUE THREAD

**Issue by SebBehrendt** [eclipse-basyx/basyx-java-sdk#123]
Hi,

I'm trying to push AASs to a remote AAS server that is hosted on a cloud platform. The server is the default version from docker hub (eclipsebasyx/aas-server:1.2.0).  I created AASs with lambda properties and operations based on the provided BaSyx examples (https://wiki.eclipse.org/BaSyx_/_Examples) and use the example code snippts to push the AASs and associated submodels to the server. So far, the push is working correctly and the AASs are on the remote server. However,  when I want to request the submodelelements, the dynamic behavior is not working. E.g. the result of a get request to a lambda property returns the following:
`{"modelType":{"name":"Property"},"kind":"Instance","value":{"get":"_basyxInvocable"},"idShort":"dummy","valueType":"boolean","parent":{"keys":[{"type":"Submodel","local":true,"value":"","idType":"IRDI"}]}}`

Is there another way to add operations and lambda properties to a remote server without any operation delegation?

Thank you very much.

Yours sincerely,
Sebastian Behrendt

**Comment by FrankSchnicke** [comment]
We're only supporting active code on an AAS Server if the server is started programatically. In theory, pushing runtime behavior on an already running server would be possibel - however, this can very quickly turn into a security issue.

The [Cloud-Edge-Deployment example](https://github.com/eclipse-basyx/basyx-java-examples/tree/main/basyx.examples/src/main/java/org/eclipse/basyx/examples/scenarios/cloudedgedeployment) illustrates how to start the server programmatically.
