### ISSUE TITLE
SubmodelElementList missing in Basyx

### ISSUE THREAD

**Issue by nqduy35** [eclipse-basyx/basyx-java-sdk#153]
I cannot find SubmodelElementList in the code and the Wiki's Basyx. I guess that you have not implemented it yet. 
Do you plan to add SubmodelElementList to Basyx in the near future?

**Comment by FrankSchnicke** [comment]
SubmodelElementList was introduces with the release candidates of Version 3 of the meta model. BaSyx right now is supporting Version 2.0.1.

We're planning to switch with the next major release (i.e., 2.0.0) to meta model V3 by utilizing [AAS4J](https://github.com/eclipse-aas4j) which is also being co-developed by us.
