### ISSUE TITLE
Case of "anyURI" seems to be wrong when serializing an AAS submodel

### ISSUE THREAD

**Issue by HansG89** [eclipse-basyx/basyx-java-sdk#155]
I came accross this error when trying to use the Submodel Client from BaSyx .NET.   
When an AAS contains a property of type "AnyURI", the json representation of this property is "anyuri" instead of "**anyURI**". On the client side the deserialization will fail.

From the outside perspective it looks like this line of code seems to be the problem:
https://github.com/eclipse-basyx/basyx-java-sdk/blob/469032319eca85bac87faa535365ba2eab8292d3/src/main/java/org/eclipse/basyx/submodel/metamodel/map/submodelelement/dataelement/property/valuetype/ValueType.java#L39

**Comment by FrankSchnicke** [comment]
Thank you very much for pointing this out. We will double-check any implications changing this will have and then fix it accordingly.

**Comment by FrankSchnicke** [comment]
According to the official spec V2.0.1, "anyUri" would be correct. However, this seems to be a bug since (a) in XML it is using "anyURI" and (b) in V3RC02 it is also "anyURI". Due to compatibility reasons with the dotnet SDK, we chose "anyURI" as fix.
