### ISSUE TITLE
AASXToMetamodelConverter unzips files to rootFolder

### ISSUE THREAD

**Issue by msiebert-dev** [eclipse-basyx/basyx-java-sdk#164]
Currently files unzipped by `public void unzipRelatedFiles()` in [AASXToMetamodelConverter.java](https://github.com/eclipse-basyx/basyx-java-sdk/blob/main/src/main/java/org/eclipse/basyx/aas/factory/aasx/AASXToMetamodelConverter.java#L242) are stored in the rootFolder. 

Wouldn't it be better to store the files in a temporary directory? The rootFolder ends up being the local maven repository.

**Comment by FrankSchnicke** [comment]
Thanks for pointing this out. You're right, storing it in a temporary directory would be a better way of handling this.
If you would like to, feel free to raise a PR.

**Comment by FrankSchnicke** [comment]
Implemented by merged pull request. Thanks a lot!
