### ISSUE TITLE
Is there a Schema Definition for the APIs?

### ISSUE THREAD

**Issue by scharf** [eclipse-basyx/basyx-java-sdk#171]
[I have extracted the JSON Schema](https://gist.github.com/scharf/8f9a3f9d007077ff7745935580ed0520) from [SPECIFICATION Details of the Asset Administration Shell](https://www.plattform-i40.de/IP/Redaktion/DE/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part1_V2.pdf?__blob=publicationFile&v=6) (p.232 ff).

How compatible is this implementation with the JSON Schema?

**Comment by FrankSchnicke** [comment]
In the schema itself there is a small error in regard to anyUri (cf. the discussion in https://github.com/eclipse-basyx/basyx-java-sdk/issues/155). Besides that I'm not aware of any inconsistencies. 

Please note that the JSON Schema is specifying the overall AAS Environment schema, not the schema of a payload of a Submodel request etc.
