### ISSUE TITLE
Java SDK Setup not up-to-date

### ISSUE THREAD

**Issue by Deputy-Chief-Hardy** [eclipse-basyx/basyx-java-sdk#211]
Hello, I am referring to this wiki-page: https://wiki.eclipse.org/BaSyx_/_Download_/_Java_Setup

In the beginning it was necessary to clone three Github repositories (basyx-java-sdk, basyx-components, basyx-examples) to get the same selection as on the screenshot "Import Maven Projects". This doesn't get very clear from the instructions. :)

Second I had some issues during installing the basyx-java-sdk: 
On the following page about the components setup (https://wiki.eclipse.org/BaSyx_/_Download_/_Components_Setup) it says _Save the following commands to an arbitrary text file. Next, import the database through psql -U postgres -f "your-file"._
Is meant by "your-file" the setup_postgres.sql in the bin folder of Postgres?

Third installing the Maven project basyx-components works properly (step 4 under _Project Installation_), but installing basyx-examples leads to the following error:

![Screenshot build failure](https://user-images.githubusercontent.com/49750085/212851229-279ef6aa-bafb-4b44-a604-90bbb6ebe689.PNG)

Do you have an idea how to fix this?

**Comment by FrankSchnicke** [comment]
This ticket is missing any description - did you delete it by accident?

**Comment by Deputy-Chief-Hardy** [comment]
Hi @FrankSchnicke you are right, I deleted it by accident and updated the description now. Cheers

**Comment by FrankSchnicke** [comment]
>  In the beginning it was necessary to clone three Github repositories (basyx-java-sdk, basyx-components, basyx-examples) to get the same selection as on the screenshot "Import Maven Projects". This doesn't get very clear from the instructions. :)

Thanks for pointing this out, I adapted the description.


> On the following page about the components setup (https://wiki.eclipse.org/BaSyx_/_Download_/_Components_Setup) it says Save the following commands to an arbitrary text file. Next, import the database through psql -U postgres -f "your-file".
Is meant by "your-file" the setup_postgres.sql in the bin folder of Postgres?

"your-file" means the arbitrary text file in one step beforehand. I adapted the description to make this more clear.
By the way, there's no need to build components if you just want to utilize the released components. They are available on [DockerHub](https://hub.docker.com/search?q=eclipsebasyx).

> Third installing the Maven project basyx-components works properly (step 4 under Project Installation), but installing basyx-examples leads to the following error:

I guess examples installation is failing because you're missing a dependency, most likely related to authorization. The installation of the examples project is not necessary, it can be used without installation. Thus, this should be no issue.

Does this answer your questions? If yes, feel free to close this ticket.

**Comment by Deputy-Chief-Hardy** [comment]
Hi @FrankSchnicke, thanks for your answer! I am a little confused what to do. In the basyx wiki it often says that the Java SDK and the components must be installed. But when I follow the link then there is the setup page, where it says at once that building is only necessary in case of ... so what is the difference between building and installing? It doesn't get that clear which steps must be executed in any case.

**Comment by FrankSchnicke** [comment]
I somehow missed your response - apologies for the delay.

Building/Installing is only necessary if you would like to modify code in the SDK/Components. If you would like to work with the SDK/Components, you can utilize the artifacts on Maven Central or on DockerHub.

Thus, depending on your use case, building/installing is not needed.

**Comment by Deputy-Chief-Hardy** [comment]
Okay thanks, I will try it!
