### ISSUE TITLE
Trying to reproduce Basic Example (https://wiki.eclipse.org/BaSyx_/_Introductory_Examples)

### ISSUE THREAD

**Issue by Deputy-Chief-Hardy** [eclipse-basyx/basyx-java-sdk#212]
Hi, I am trying to reproduce the steps of the basic example, so that I can execute all 8 steps. 
At step 3 I do not know what to do, it doesn't get that clear in the wiki. Do I have to copy the code or is it somewhere in the repo? If I have to copy, what imports do I need and how does the directory structure must look like at the end? I appreciate any help. Cheers

**Comment by FrankSchnicke** [comment]
Hi, you have to copy the code and set it up in your own environment. Then, the IDE should automatically resolve the imports.
If you would like to have a running example that is also in the repository, you can take a look at the scenarios - e.g., https://wiki.eclipse.org/BaSyx_/_Scenarios_/_Cloud_Edge_Deployment
