### ISSUE TITLE
Simple JWT architecture in the future?

### ISSUE THREAD

**Issue by nqduy35** [eclipse-basyx/basyx-java-sdk#213]
I found that BaSyx supports JWT. But the architecture you propose is too complex (RS256 algo + JWKS server). I don't know if you have a plan to proposes a simple option: HS256 + the AAS Server proposes directly JWTs instead of using a JWKS server ?

**Comment by FlorianWege-IESE** [comment]
Hello. Sorry for the late response.

I am not sure exactly what you mean by 'complex'. And do you refer to the SDK or Off-the-Shelf AAS Server component (which is more opinionated and trying to provide solutions that are easier to use)?

We use JWT-based OAuth, which distinguishes between auth servers issuing the tokens and resource servers being presented the tokens https://www.rfc-editor.org/rfc/rfc6749#section-1.1. If I understand you right, the resource servers should be able to issue tokens on their own? BaSyx currently has no specific facilities to generate JWTs (unless by dependencies), only means to request tokens from an auth server before making calls to other resource servers.

A fixation on RS256 I see is here https://github.com/eclipse-basyx/basyx-java-sdk/blob/57d8d45374d4f9603bc2df0992a7fe41f553594f/src/main/java/org/eclipse/basyx/vab/protocol/http/server/BaSyxHTTPServer.java#L241 currently but that could probably be easily flexibilized to allow other signature algorithms.

With the symmetric key for HMAC distributed to different servers, however, one would have to be careful that it does not get leaked/abused and compromise the whole network that shares the key and the unique identification of the issuer would be lost, would it not? And key rotation and securely storing the key will get more complicated.

If the key was only kept at the issuer on the other hand, the receiving resource server would need to call back for verification. Maybe that's not less simple than the asymmetric/JWKS approach.

There have been no plans for symmetric signing/verification so far but we are exploring security controls for BaSyx.

**Comment by nqduy35** [comment]
Thank you for your informative answer. I understand that you follow the standard for the best implementation. And you are right: I'm looking for a solution that omits implementing the auth server and using the symmetric key.
