### ISSUE TITLE
Basyx SDK should not depend on Apache Tika (tika-core) (only uses "mime" package)

### ISSUE THREAD

**Issue by in-fke** [eclipse-basyx/basyx-java-sdk#266]
Apparently, the Basyx SDK depends on Apache Tika (tika-core) only for these classes.
Used by `VABSubmodelAPI`. Maybe there is a way of getting rid of this dependency?
That Jar file has roughly 700kb https://repo1.maven.org/maven2/org/apache/tika/tika-core/2.7.0/

```
import org.apache.tika.mime.MimeType;
import org.apache.tika.mime.MimeTypeException;
import org.apache.tika.mime.MimeTypes;
```

**Comment by FrankSchnicke** [comment]
We need this dependency for handling file extensions with the file storage feature. Unfortunately, I'm not aware of any other library delivering the needed feature of Mimetype to file extension mapping.

**Comment by in-fke** [comment]
Tja, ich habe leider auch kein Patentrezept, und der Punkt ist sicher nicht so dringend, sofern BaSyx containerisiert zum Einsatz kommt. Was ich dazu gefunden habe: https://www.baeldung.com/java-file-mime-type (wobei https://mvnrepository.com/artifact/net.sf.jmimemagic/jmimemagic auch nicht vielversprechend aussieht, wurde seit 6 jahren nicht mehr aktualisiert).
