### ISSUE TITLE
AASXToMetamodelConverter.unzipFile() too verbose with INFO

### ISSUE THREAD

**Issue by in-fke** [eclipse-basyx/basyx-java-sdk#272]
Using `unzipRelatedFiles` on "01_Festo.aasx" produces 30 lines of INFO log.
These should rather be `DEBUG`.

https://github.com/eclipse-basyx/basyx-java-sdk/blob/main/src/main/java/org/eclipse/basyx/aas/factory/aasx/AASXToMetamodelConverter.java#L354

`logger.info("Unzipping " + filePath);`

https://github.com/eclipse-basyx/basyx-java-sdk/blob/main/src/main/java/org/eclipse/basyx/aas/factory/aasx/AASXToMetamodelConverter.java#L360

`logger.info("Unzipping to " + destDir);`

This may seem picky, but in my opinion "regular" operations should not produce as much log output in order to keep log output more readable.

I can make PRs for such things - but let's get to know each other first ;)

**Comment by FrankSchnicke** [comment]
Fixed, thanks for pointing this out!
