### ISSUE TITLE
Unable to access the AAS data

### ISSUE THREAD

**Issue by spnazf** [eclipse-basyx/basyx-java-sdk#307]
Hi, I am facing the following issues

1. Trying to access the following AAS data using the id **aasServer/shells/www.company.com/ids/aas/8003_4110_1102_9521**** even though I encode the assId that is in the URL format  **aasServer/shells/www.company.com%2Fids%2Faas%2F8003_4110_1102_9521** I am getting error 
![image](https://github.com/eclipse-basyx/basyx-java-sdk/assets/107242911/84ffbd79-6c47-4cc8-b21f-e751e2cf40d4)

2. The submodel information could not be retrieved. Getting the following error
![image](https://github.com/eclipse-basyx/basyx-java-sdk/assets/107242911/1ea44c2c-de5f-45ff-8dc9-a6e2ac7053d3)

**Comment by spnazf** [comment]
I am unable to access the following url with the below AASID(text in bold) 
/aasServer/shells/**www.company.com/ids/aas/8003_4110_1102_9521**

Following is the submodel URL that's not working as expected but a different AAS id data
http://svc-ezd-basyx-server-ocp050149.apps.titan.hco000139.mars.cloud.zf-world.com/aasServer/shells/AssetAdministrationShell---6003FF71/aas/submodels/Pr%C3%BCfstandszustand

**Comment by FrankSchnicke** [comment]
Would it be possible to describe your usage of BaSyx SDK more into detail? Are you utilizing the Docker Images, are you setting up the tomcat using the servlets, etc.?

>  /aasServer/shells/AssetAdministrationShell---6003FF71/aas/submodels/Pr%C3%BCfstandszustand

'Pr%C3%BCfstandszustand' is the idShort of your submodel, correct? You are missing the "/submodel" suffix in the URL.

**Comment by spnazf** [comment]
We are using the docker version of the Basyx SDK and as you mentioned I have already tried the API with submodel but still the issue exist

**URL** : /aasServer/shells/AssetAdministrationShell---6003FF71/aas/submodels/Prüfstandszustand/submodel

**Error Msg:**

{"success":false,"isException":true,"messages":[{"messageType":6,"code":"404","text":"ResourceNotFoundException: Could not resolve Submodel with idShort Pr%C3%BCfstandszustand for AAS {idType\u003dCustom, id\u003dAssetAdministrationShell---6003FF71}"}]}

**Comment by FrankSchnicke** [comment]
Thanks for providing these details. Would it be possible to provide an executable example reproducing your issue? I will then gladly take a look

**Comment by FrankSchnicke** [comment]
Is this still of relevance for you? If no, I will close this issue in a few days.
