### ISSUE TITLE
Qualifiable.getQualifiers() always returns an empty LinkedHashSet

### ISSUE THREAD

**Issue by HoferXitaso** [eclipse-basyx/basyx-java-sdk#326]
# How to reproduce

1. Create a AASX file using the AASX Package Explorer with an Operation in a Submodel
2. Add a Quailfier "invocationDelegation" to the Operation
3. Export the Submodel to JSON
5. Put the Submodel in form of a JSON inside a AAS hosted in BaSyx
6. Try to invoke the Operation

# The error

When trying to invoke the function you will get an answer, that it is not possible for that path, because `Qualifiable.getQualifiers` always returns an empty LinkedHashSet

# Proposed solution

The BaSyx backend checks, if the operation is a delegated one (undelegated operations are not yet supported AFAIK).
To check that, the `OperationProvider.invokeOperation` calls `DelegatedInvocationManager.isDelegatingOperation`.
Here it gets all qualifiers from the operation and tries to find one that has the above mentioned qualifier in it.
Problem is, that when calling `operation.getQualifiers` it tries to retrieve the field with the name "`qualifiers`" (`Qualifiable.QUALIFIERS`). But when looking at the json (and thus the internal representation), there is no field "`qualifiers`" as it is called "`constraints`"

![image](https://github.com/eclipse-basyx/basyx-java-sdk/assets/139554944/6b7bc505-7113-4332-951d-e9f28313a3dc)
![image](https://github.com/eclipse-basyx/basyx-java-sdk/assets/139554944/c8e992df-3cf6-4363-b8cc-39540b6051d1)
![image](https://github.com/eclipse-basyx/basyx-java-sdk/assets/139554944/3f4b85be-a3f2-4e07-ae5e-46e1e608f62f)

A quick fix would be to set `Qualifiable.QUALIFIERS` to `"constraints"` and possibly renaming `Qualifiable.QUALIFIERS` to `Qualifiable.CONSTRAINTS`

![image](https://github.com/eclipse-basyx/basyx-java-sdk/assets/139554944/d465fe5f-d1ee-4c3a-b4fa-eec457b81dc6)

# Additional remarks

It could also be an error coming from the AASX Package Explorer, if so I will post my issue there.

**Comment by FrankSchnicke** [comment]
This seems to be a bug in the AASX Package Explorer. If you take a look at DotAAS Part 1 V2.0.1 p. 233 following, this is stated:


```
"Qualifiable": {
	"type": "object", 
	"properties": { 
		"qualifiers": { 
			"type": "array", 
			"items": { "$ref": "#/definitions/Constraint" } 
		} 
	} 
}
```

**Comment by FrankSchnicke** [comment]
Closed as not related to BaSyx.
