### ISSUE TITLE
Timeline for AAS Meta-Model Update

### ISSUE THREAD

**Issue by alw-iwu** [eclipse-basyx/basyx-java-sdk#45]
Hi - we're looking into Basyx to use it in a research project. Can you make a statement about the current version of the AAS-Meta-Model and (if necessary) plans to update it to V3RC01?

**Comment by FrankSchnicke** [comment]
BaSyx right now supports the AAS Metamodel as specified in DotAAS Part 1 V2.0.1.

Right now, we're involved with IDTA to implement the AAS Repository (AAS Aggregator in BaSyx) using the newest release of the meta model, i.e., currently V3RC02, utilizing the [AAS Models in Java](https://github.com/admin-shell-io/java-model) library. Thus, BaSyx will support Version 3 in future. 

This of course leads to the question what will happen with applications using the old meta model after this transition. 
We're currently discussing this internally. Most likely, we will provide API gateways that (i) map the HTTP/REST API as well as (ii) map the different version of the meta model. Of course, there are some parts of the new meta model that can't be mapped automatically. However, from our experience, these parts are typically not mission-critical for applications.

Thus, applications using the older meta model will still be compatibly with applications of the new meta model and not "stuck" on an older version.

**Comment by alw-iwu** [comment]
Thanks for the explanation - we're looking forward to new releases then!
