### ISSUE TITLE
SubmodelProvider provided idShortPath incorrect

### ISSUE THREAD

**Issue by FlorianWege** [eclipse-basyx/basyx-java-sdk#60]
According to the API docs, the path for invoking an operation is

`/shells/{aasId}/aas/submodels/{submodelIdShort}/submodel/submodelElements/{idShortPathToOperation}/invoke`

or for the async-variant 

`/shells/{aasId}/aas/submodels/{submodelIdShort}/submodel/submodelElements/{idShortPathToOperation}/invoke?async=true`

In the oven example imagine it instanced like

`/shells/eclipse.basyx.aas.oven/aas/submodels/Oven/submodel/submodelElements/activateOven/invoke`

Expected: Here, the idShortPath should be `activateOven`.

Problem: The org.eclipse.basyx.submodel.restapi.SubmodelProvider class forwards incorrect idShortPaths of the submodel element to the enclosed ISubmodelAPI. In the example, instead of `activateOven`, it forwards `/activateOven/invoke`, not having removed the trailing `/invoke`.

In the async invoke case, it forwards `/activateOven/`, having removed the trailing `invoke` but not the trailing slash.

For other methods, those don't have a trailing path segment to be removed, but more precisely, for all methods, imho the leading slash should also be removed for consistency with the URL pattern, so it should be `activateOven` instead of `/activateOven`.

See https://github.com/eclipse-basyx/basyx-java-sdk/blob/754b1c11e9961822b6dad28b4837103a9cde745e/src/main/java/org/eclipse/basyx/submodel/restapi/SubmodelProvider.java#L253

It can be seen that in the async-branch, there is an instruction to remove the trailing part, which is missing in the else-branch for non-async invocations.

**Comment by FrankSchnicke** [comment]
Many thanks for pointing this out. We will fix this soon.
